config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # devise_scope  :user do
  #   get 'users/sign_out' => 'devise/sessions#destroy'
  # end

  get 'users/index'
  get 'users/show'
  get 'posts/index'
  get 'posts/show'
  root 'users#index'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :form, :create]
  end

  resources :posts do
    resources :comments, only: [:create]
    resources :likes, only: [:create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'authorId'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'

  after_save :update_counter

  def update_counter
    post.increment!(:commentsCounter)
  end
end

# Create comment
# Comment.create(Post: first_post, Author: second_user, Text: 'Hi Tom!' )#

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'authorId'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'

  after_save :update_counter

  def update_counter
    post.increment!(:likesCounter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'authorId'
  has_many :comments, class_name: 'Comment', foreign_key: 'authorId'
  has_many :likes, class_name: 'Like', foreign_key: 'authorId'

  validates :title, presence: true, length: { maximum: 250 }
  validates :commentsCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likesCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_counter

  def update_counter
    user.increment!(:postsCounter)
  end

  def recent_comment
    comments.includes(:user).order(created_at: :desc).limit(5)
  end
end

# Create post.
# first_post = Post.create(Author: user, Title: 'Hello', Text: 'This is my first post')

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  has_many :posts, class_name: 'Post', foreign_key: 'authorId'
  has_many :comments, class_name: 'Comment', foreign_key: 'authorId'
  has_many :likes, class_name: 'Like', foreign_key: 'authorId'
  before_validation :default_values

  validates :name, presence: true
  validates :postsCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def default_values
    self.postsCounter = 0
    self.photo = 'https://img.myloview.com/posters/social-media-user-icon-default-avatar-profile-image-400-251200036.jpg'
  end

  def recent_post
    posts.order(created_at: :desc).limit(3)
  end

  def all_posts
    posts.order(created_at: :desc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name bio email password password_confirmation])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.create(comment_params)
    @comment.user = current_user
    @comment.post = @post
    if @comment.save
      flash[:success] = 'New Comment created successfully'
      redirect_to user_post_path(current_user, @post)
    else
      flash.now[:error] = 'An error occurred : Comment could not be created'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = Like.create
    @like.user = current_user
    @like.post = @post
    if @like.save
      flash[:success] = 'Like Added successfully'
      redirect_to user_post_path(current_user, @post)
    else
      flash.now[:error] = 'An Error occurred: Like could not be saved'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    @comments = @post.comments.includes(:user)
  end

  def create
    @post = Post.create(post_params)
    @post.user = current_user
    respond_to do |format|
      format.html do
        if @post.save
          flash[:success] = 'New Post created successfully'
          redirect_to user_posts_path(current_user)
        else
          flash.now[:error] = 'An error occurred : Post could not be created'
        end
      end
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
     <%# <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%# <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container-fluid bg-success text-dark bg-opacity-25">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/partials/_comment.html.erb
<% if post.comments.count > 0 %>
  <% post.recent_comment.each do |comment| %>
    <p><%= comment.user.name %> : <%= comment.text%></p>
  <% end %>
<% else %>
  <p>No comments!</p>
<% end %>

app/views/partials/_new.html.erb
<div >
  <%= form_with model: Comment, url: post_comments_path(@post.user, @post), method: :post do |form| %>
    <%= form.text_field :text, placeholder: 'Your comment here...' %>
    <%= form.submit "Add a comment" %>
  <% end %>
</div>

app/views/partials/_post.html.erb
<h1><%= post.id%> </h1>
<h3><%= post.title%> </h3>
<%= post.text %>
<p >Comments: <span><%= post.comments.count %></span>, Likes: <span><%= post.likes.count %></span></p>

app/views/partials/_post_helper.html.erb
<div class="row  px-5 border">
  <div class="col-12 align-self-start"><h5>Title : <%= post.title%> </h5></div>
  <div class="col-12">
    <% if post.text.length > 110 %>
      <%= truncate(post.text, length: 110) ... %>
    <% else %>
      <%= post.text %>.
    <% end %>
  </div>
  <div class="col-12 align-self-end">
    <p>Comments: <span><%= post.comments.count %></span>, Likes: <span><%= post.likes.count %></span></p>
  </div>

  
</div> 

app/views/partials/_user.html.erb
<div class="row justify-content-evenly p-3">
    <div class="col-md-2 border border-dark p-2">
        <img src=<%= user.photo %> alt= '<%= user.name + ' profile'%>' class="img-fluid rounded mx-auto d-block"/>
    </div>
    <div class="col-md-8 border border-dark p-2">
        <h4><%= user.name %></h4>   
        <p>Number of posts: <%= user.posts.count%></p>
    </div>
</div>

app/views/posts/index.html.erb
<%= render "partials/user", user: @user %>
<% @posts.each do |post| %>
<%= link_to(user_post_path(@user, post)) do %>
    <%= render partial: 'partials/post', locals: {post: post} %>
        <%= render partial: 'partials/comment', locals: {post: post} %>
    <% end %>
<% end  %>
<a class="btn btn-info" >Pagination</a>

app/views/posts/new.html.erb
<div>
  <h1>Create a Post </h1>
  <%= form_with model: Post, method: :post do |form| %>
    <%= form.label :title %>
    <%= form.text_field :title, placeholder: 'Post title ...' %><br />
    <%= form.label :text, "Post" %>
    <%= form.text_area :text, placeholder: 'Post here...' %><br />
    <%= form.submit "Post Now" %>
  <% end %>
</div>

app/views/posts/show.html.erb
<%= render "partials/user", user: @user %>

<p><%= @post.title %> by <%= @post.user.name%></p>
<p>Comments: <span><%= @post.comments.count %></span>, Likes: <span><%= @post.likes.count %></span></p>

<%= @post.text %>
    <%= form_with model: Like, url: post_likes_path(@post.user, @post), method: :post do |form| %>
    <% form.submit "Like" %>
<% end %>

<% if @comments.length > 0 %>
    <% @comments.each do |comment| %>
    <p><%= comment.user.name %> : <%= comment.text %></p>
<% end %>
    <% else %>
    <p>There are no comments !!</p>
<% end %>
<div>
    <h3>Add a comment</h3>
    <%= render partial: 'partials/new' %>
</div>

app/views/users/index.html.erb
<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<%= button_to "logout", destroy_user_session_path, method: :delete  %>

<% @users.each do |user| %>
    <%= link_to "/users/#{user.id}" do%>
        <%= render partial: 'partials/user', locals: {user: user} %>
    <% end  %>
<% end %>

app/views/users/show.html.erb
<div>
  <%= render partial: 'partials/user', locals: {user: @user} %>
  <div class="row justify-content-center mx-5">
    <p class="col-">Bio:
      <%= @user.bio %>
    </p>
  </div>

  <% if @user.posts.count < 0 %>
    <p><%= @user.name %>
      doesn't have a post !></p>
  <% else %>
    <% @user.recent_post.each do |post| %>
      <%= link_to(user_post_path(@user, post)) do %>
        <%= render partial: 'partials/post_helper', locals: {post: post} %>
      <% end %>
    <% end %>
    <%= link_to("See all posts", user_posts_path(@user), class: "btn btn-success") %>

  <% end %>
</div>